spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: customer-service
          - uri: lb:http
  application:
    name: gateway-service
server:
  port: 8222
