spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: gateway-service

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
